---
- name: "Add users"
  user:
    state: present
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    update_password: on_create
  with_items:
    - "{{ users }}"
  # users is defined and not empty
  when:
    - users is defined and users
